name: Update Crypto Index

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate crypto index assets
        env:
          PYTHONPATH: src
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m crypto_index_analyzer.run --config config.yaml --output reports/crypto_index.md

      - name: Ensure .nojekyll
        run: |
          mkdir -p docs
          touch docs/.nojekyll

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git status --porcelain | grep .; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add reports/crypto_index.md reports/crypto_index.json reports/crypto_index_history.csv docs/
            git commit -m "chore: auto-update crypto rankings"
            git push
          else
            echo "No changes to commit"
          fi
